### ISSUE TITLE
Performance/InefficientHashSearch auto-correct fails with undefined method `loc' for nil:NilClass

### ISSUE THREAD

**Issue by bayandin** [rubocop-hq/rubocop#6067]
Rubcop fails to auto-correct Performance/InefficientHashSearch, _probably_ it happens when array has name `keys`.

--------

## Expected behavior

rubocop auto-fixes code

## Actual behavior

rubocop crashes

## Steps to reproduce the problem

```
$ cat rubocop_example.rb 

def keys
  []
end

def my_include?(key)
  keys.include?(key)
end
```

```
$ rubocop --debug --auto-correct rubocop_example.rb --only Performance/InefficientHashSearch 

For /Users/bayandin: configuration from /usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/config/default.yml
Inheriting configuration from /usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/config/enabled.yml
Inheriting configuration from /usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/config/disabled.yml
Inspecting 1 file
Scanning /Users/bayandin/rubocop_example.rb


0 files inspected, no offenses detected
undefined method `loc' for nil:NilClass
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/performance/inefficient_hash_search.rb:90:in `autocorrect_hash_expression'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/performance/inefficient_hash_search.rb:54:in `block in autocorrect'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/corrector.rb:61:in `block (2 levels) in rewrite'
/usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/source/tree_rewriter.rb:220:in `transaction'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/corrector.rb:60:in `block in rewrite'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/corrector.rb:58:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/corrector.rb:58:in `rewrite'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:126:in `autocorrect_all_cops'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:70:in `autocorrect'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:98:in `block in offenses'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:115:in `investigate'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:94:in `offenses'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:44:in `inspect_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:265:in `inspect_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:212:in `block in do_inspection_loop'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:244:in `block in iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:237:in `loop'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:237:in `iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:208:in `do_inspection_loop'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:111:in `block in file_offenses'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:129:in `file_offense_cache'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:109:in `file_offenses'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:100:in `process_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:75:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:75:in `reduce'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:75:in `each_inspected_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:67:in `inspect_files'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:39:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cli.rb:160:in `execute_runner'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cli.rb:88:in `execute_runners'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cli.rb:41:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/exe/rubocop:13:in `block in <top (required)>'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/exe/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<main>'
Finished in 0.3469570000306703 seconds
```

## RuboCop version

```
$ rubocop -V
0.57.2 (using Parser 2.5.1.0, running on ruby 2.5.1 x86_64-darwin17)
```

**Comment by bayandin** [comment]
Actually, probably this cop even shouldn't be triggered because of `keys` — it is an array, not a hash

**Comment by koic** [comment]
Essentially, static analysis targeted by RuboCop does not know the type determined at run-time.
It would be better to work on a different approach to solving this problem.

**Comment by rrosenblum** [comment]
> Probably this cop even shouldn't be triggered because of `keys` — it is an array, not a hash

> It would be better to work on a different approach to solving this problem.

I think this would be relatively easy to check for and prevent. Since `keys` is a top level variable, we can treat this as a normal call `include?` on a variable named `keys`. The only down side would be that this cop wouldn't work on classes that extend `Hash`. Essentially the cop should only trigger on `<something>.keys.include?`.
