### ISSUE TITLE
Cop `Gemspec/OrderedDependencies` breaks when parsing a frozen gem name.

### ISSUE THREAD

**Issue by gdeoliveira** [rubocop-hq/rubocop#6086]
## Expected behavior

`Gemspec/OrderedDependencies` parses frozen gem names correctly.

## Actual behavior

The cop chokes when trying to call `downcase` after parsing a frozen gem name. The problem seems to come from [this line of code](https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/mixin/ordered_gem_node.rb#L40) since `str_content` returns `nil` for a gem name that is explicitly frozen.

Stack trace of the error:

```
NoMethodError:
  undefined method `downcase' for nil:NilClass

./lib/rubocop/cop/mixin/ordered_gem_node.rb:19:in `case_insensitive_out_of_order?'
./lib/rubocop/cop/gemspec/ordered_dependencies.rb:67:in `block in investigate'
./lib/rubocop/cop/gemspec/ordered_dependencies.rb:104:in `block in dependency_declarations'
./lib/rubocop/ast/node.rb:575:in `block in visit_descendants'
./lib/rubocop/ast/node.rb:185:in `block in each_child_node'
./lib/rubocop/ast/node.rb:183:in `each'
./lib/rubocop/ast/node.rb:183:in `each_child_node'
./lib/rubocop/ast/node.rb:574:in `visit_descendants'
./lib/rubocop/ast/node.rb:576:in `block in visit_descendants'
./lib/rubocop/ast/node.rb:185:in `block in each_child_node'
./lib/rubocop/ast/node.rb:183:in `each'
./lib/rubocop/ast/node.rb:183:in `each_child_node'
./lib/rubocop/ast/node.rb:574:in `visit_descendants'
./lib/rubocop/ast/node.rb:260:in `each_node'
./lib/rubocop/cop/gemspec/ordered_dependencies.rb:102:in `dependency_declarations'
./lib/rubocop/cop/gemspec/ordered_dependencies.rb:65:in `each'
./lib/rubocop/cop/gemspec/ordered_dependencies.rb:65:in `each_cons'
./lib/rubocop/cop/gemspec/ordered_dependencies.rb:65:in `investigate'
./lib/rubocop/cop/commissioner.rb:96:in `block (2 levels) in invoke_custom_processing'
./lib/rubocop/cop/commissioner.rb:105:in `with_cop_error_handling'
./lib/rubocop/cop/commissioner.rb:95:in `block in invoke_custom_processing'
./lib/rubocop/cop/commissioner.rb:92:in `each'
./lib/rubocop/cop/commissioner.rb:92:in `invoke_custom_processing'
./lib/rubocop/cop/commissioner.rb:43:in `investigate'
./lib/rubocop/rspec/cop_helper.rb:71:in `_investigate'
./lib/rubocop/rspec/cop_helper.rb:25:in `inspect_source'
./lib/rubocop/rspec/expect_offense.rb:61:in `expect_no_offenses'
```

## Steps to reproduce the problem

Attempt to run Rubocop with a gemspec file like the following:

```
spec.add_development_dependency "rspec".freeze
spec.add_development_dependency "rubocop".freeze
```

## RuboCop version

```
$ rubocop -V
0.58.0 (using Parser 2.5.1.0, running on ruby 2.5.1 x86_64-linux-musl)
```

**Comment by koic** [comment]
Thanks for the feedback. I confirmed this reproduction and I opened a PR #6087.
