### ISSUE TITLE
Error with 'Style/For' cop: undefined method `end' for #<Parser::Source::Map::Operator:...>

### ISSUE THREAD

**Issue by cesarizu** [rubocop-hq/rubocop#6316]
When running rubocop on loops like:

```ruby
for a in 1...some_var
    do_something(a)
end
```

## Expected behavior

It should autocorrect to `each` like this:

```ruby
(1...some_var).each do |a|
    do_something(a)
end
```
## Actual behavior

I get the following exception:

```
An error occurred while Style/For cop was inspecting /home/user/src/test.rb:3:0.
undefined method `end' for #<Parser::Source::Map::Operator:0x00000000024446c8>
Did you mean?  send
/home/user/.rvm/gems/ruby-2.4.4@default/bundler/gems/rubocop-b835bc6c5781/lib/rubocop/cop/style/for.rb:103:in `autocorrect_to_each'
/home/user/.rvm/gems/ruby-2.4.4@default/bundler/gems/rubocop-b835bc6c5781/lib/rubocop/cop/style/for.rb:86:in `autocorrect'
/home/user/.rvm/gems/ruby-2.4.4@default/bundler/gems/rubocop-b835bc6c5781/lib/rubocop/cop/cop.rb:153:in `correct'
/home/user/.rvm/gems/ruby-2.4.4@default/bundler/gems/rubocop-b835bc6c5781/lib/rubocop/cop/cop.rb:131:in `add_offense'
/home/user/.rvm/gems/ruby-2.4.4@default/bundler/gems/rubocop-b835bc6c5781/lib/rubocop/cop/style/for.rb:63:in `on_for'
```

## Steps to reproduce the problem

Just run `rubocop -a` on any file with the provided example using the default configuration.

## RuboCop version

```
$ [bundle exec] rubocop -V
0.59.1 (using Parser 2.5.1.2, running on ruby 2.4.4 x86_64-linux)
```

Running directly from github code, git commit: b835bc6c5781

**Comment by Drenmi** [comment]
Thanks for the report! Bug verified in latest `master`.
