### ISSUE TITLE
Layout/CommentIndentation: Infinite loop detected

### ISSUE THREAD

**Issue by aried3r** [rubocop-hq/rubocop#6373]
## Expected behavior

RuboCop should correct the comment indentation in the file below.

## Actual behavior

RuboCop only corrects part of the file, then crashes.

```
Infinite loop detected in /ruby-vips/lib/vips/methods.rb.
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:245:in `block in iterate_until_no_changes'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:241:in `loop'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:241:in `iterate_until_no_changes'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:212:in `do_inspection_loop'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:115:in `block in file_offenses'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:133:in `file_offense_cache'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:113:in `file_offenses'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:101:in `process_file'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:75:in `each'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:75:in `reduce'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:75:in `each_inspected_file'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:67:in `inspect_files'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/runner.rb:39:in `run'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/cli.rb:157:in `execute_runner'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/cli.rb:85:in `execute_runners'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/lib/rubocop/cli.rb:41:in `run'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/exe/rubocop:13:in `block in <top (required)>'
/ruby/2.5.0/benchmark.rb:308:in `realtime'
/ruby/gems/2.5.0/gems/rubocop-0.59.2/exe/rubocop:12:in `<top (required)>'
.rbenv/versions/2.5.1/bin/rubocop:23:in `load'
.rbenv/versions/2.5.1/bin/rubocop:23:in `<top (required)>'
/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `load'
/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:28:in `run'
/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli.rb:424:in `exec'
/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'
/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'
/ruby/gems/2.5.0/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'
/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/ruby/gems/2.5.0/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
.rbenv/versions/2.5.1/bin/bundle:23:in `load'
.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
```

## Steps to reproduce the problem

Running
```
rubocop -a --only Layout/CommentIndentation lib/vips/methods.rb
```

on this file: https://github.com/libvips/ruby-vips/blob/55759db160d5e692b9e5b12a881ac2c74cf3e951/lib/vips/methods.rb makes it misbehave.

Note: If you don't just copy this file but clone the repo you have to uncomment or delete the `Layout/CommentIndentation` cop in `.rubocop_todo.yml`.

## RuboCop version

```console
$ rubocop -V
0.59.2 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin16)
```

**Comment by koic** [comment]
The upper limit 200 which can be auto-correct at once is set.

```consle
% rubocop -a --only Layout/CommentIndentation lib/vips/methods.rb

(snip)

0 files inspected, 200 offenses detected, 200 offenses corrected
Infinite loop detected in /private/tmp/6373/lib/vips/methods.rb.
/Users/koic/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubocop-0.60.0/lib/rubocop/runner.rb:245:in `block in iterate_until_no_changes'
/Users/koic/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubocop-0.60.0/lib/rubocop/runner.rb:241:in `loop'
```

The upper limit setting is below.

```ruby
MAX_ITERATIONS = 200
```

https://github.com/rubocop-hq/rubocop/blob/v0.60.0/lib/rubocop/runner.rb#L20

There may be a clearer way than an infinite correction loop error, but I have not got any good idea yet.

**Comment by aried3r** [comment]
What would be the best way to correct files like that? Is there a way to do it in stages? Like "do line 1-200 now". Or do I have to manually repair some parts until I get less than 200 iterations? Ideally I'd have RuboCop do that, tho.

**Comment by Drenmi** [comment]
Will the [patch](https://github.com/rubocop-hq/rubocop/pull/6496) that @jonas054 provided, which batches comment auto-corrections indirectly fix this?

**Comment by jonas054** [comment]
@Drenmi My patch doesn't quite solve the problem. It takes the offense count for `Layout/CommentIndentation` in this file from 1976 to 251. So it's still over 200.

@aried3r The good news is that the next time you run, RuboCop will succeed (on latest master). With the lastest gem version, it should take 10 times. The inspected file is not corrupted by the failure. It's partly corrected.

@koic I wonder if we could detect that it's not the same line that's being corrected each iteration, that's we're actually working our way down through the file.
