### ISSUE TITLE
Question about "safe" autocorrections

### ISSUE THREAD

**Issue by searls** [rubocop-hq/rubocop#6448]
I'm still debugging what's actually happening in this case, but I'm curious how strong of a guarantee "safe" is meant to meant in rubocop.

The reason I ask, is because `Style/SymbolProc` autocorrected my code and caused a test failure and I'm unsure if that's a rubocop problem or an entirely me problem (I assume the latter and would expect this to be closed! Just checking!).

The example I'm looking at is that I have a class with these two methods:

```ruby
  def +(other)
    return self.-(other * -1) if other < 0
    other.times.reduce(self) do |memo|
      memo.next
    end
  end

  def -(other)
    return self.+(other * -1) if other < 0
    other.times.reduce(self) do |memo|
      memo.previous
    end
  end
```

This was autocorrected to:

```
app/models/week.rb:52:30: C: [Corrected] Style/SymbolProc: Pass &:next as an argument to reduce instead of a block.
    other.times.reduce(self) do |memo| ...
                             ^^^^^^^^^
app/models/week.rb:59:30: C: [Corrected] Style/SymbolProc: Pass &:previous as an argument to reduce instead of a block.
    other.times.reduce(self) do |memo| ...
                             ^^^^^^^^^
```

Resulting in the new listing:

```ruby
  def +(other)
    return self.-(other * -1) if other < 0
    other.times.reduce(self, &:next)
  end

  def -(other)
    return self.+(other * -1) if other < 0
    other.times.reduce(self, &:previous)
  end
```

However, this actually blows up when executed in my test. (Sadly, I haven't figure out why yet)

```
ArgumentError: wrong number of arguments (given 1, expected 0)
    app/models/week.rb:34:in `previous'
    app/models/week.rb:57:in `times'
    app/models/week.rb:57:in `each'
    app/models/week.rb:57:in `reduce'
    app/models/week.rb:57:in `-'
    app/models/week.rb:51:in `+'
    app/models/week.rb:90:in `find_week_by'
    app/models/week.rb:85:in `previous_week_that'
    app/models/week.rb:69:in `previous_invoice_week'
    app/controllers/invoices_controller.rb:9:in `todo'
```

**Comment by Darhazer** [comment]
This happens because `reduce` actually yields 2 parameters on the block, but you have declared only one of them. When you use `&:` it passes the second argument to the method, but the method does not expect an argument.

If you declare that the block has a second (unused) parameter however, RuboCop would not suggest using `&:`

So the correct code would be:
```ruby
def +(other)
    return self.-(other * -1) if other < 0
    other.times.reduce(self) do |memo, _current|
      memo.next
    end
  end

  def -(other)
    return self.+(other * -1) if other < 0
    other.times.reduce(self) do |memo, _current|
      memo.previous
    end
  end
```
