### ISSUE TITLE
0.61.1: Rubocop crashes with infinite ranges

### ISSUE THREAD

**Issue by dabroz** [rubocop-hq/rubocop#6617]
Test files:

```
$ cat .rubocop.yml 

AllCops:
  TargetRubyVersion: 2.6

$ cat test.rb

def foo
  bar[11..]
end
```

--------

## Expected behavior

Rubocop should work normally.

## Actual behavior

```
Inspecting 1 file


0 files inspected, no offenses detected
undefined method `type' for nil:NilClass
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/ast/traversal.rb:50:in `block in on_irange'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/ast/traversal.rb:50:in `each'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/ast/traversal.rb:50:in `on_irange'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/cop/commissioner.rb:35:in `block (2 levels) in <class:Commissioner>'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/ast/traversal.rb:107:in `block in on_send'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/ast/traversal.rb:104:in `each'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/ast/traversal.rb:104:in `each_with_index'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/ast/traversal.rb:104:in `on_send'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/cop/commissioner.rb:35:in `block (2 levels) in <class:Commissioner>'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/ast/traversal.rb:100:in `on_def'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/cop/commissioner.rb:35:in `block (2 levels) in <class:Commissioner>'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/ast/traversal.rb:13:in `walk'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/cop/commissioner.rb:46:in `investigate'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/cop/team.rb:116:in `investigate'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/cop/team.rb:104:in `offenses'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:280:in `inspect_file'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:227:in `block in do_inspection_loop'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:259:in `block in iterate_until_no_changes'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:252:in `loop'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:252:in `iterate_until_no_changes'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:223:in `do_inspection_loop'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:126:in `block in file_offenses'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:144:in `file_offense_cache'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:124:in `file_offenses'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:112:in `process_file'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:89:in `block in each_inspected_file'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:86:in `each'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:86:in `reduce'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:86:in `each_inspected_file'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:76:in `inspect_files'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/runner.rb:48:in `run'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/cli.rb:150:in `execute_runner'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/cli.rb:77:in `execute_runners'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/lib/rubocop/cli.rb:42:in `run'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/exe/rubocop:13:in `block in <top (required)>'
/Users/jablko/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/gems/rubocop-0.61.1/exe/rubocop:12:in `<top (required)>'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/bin/rubocop:23:in `load'
/Users/jablko/.rvm/gems/ruby-2.6.0@r5/bin/rubocop:23:in `<main>'
```

## Steps to reproduce the problem

After creating two files mentioned in the beginning, simply run `rubocop`.

## RuboCop version

```
$ rubocop -V
0.61.1 (using Parser 2.5.3.0, running on ruby 2.6.0 x86_64-darwin16)
```

**Comment by Drenmi** [comment]
Thanks for reporting @dabroz. 🙇
