### ISSUE TITLE
IndentationConsistency+IndentationWidth infinite loop

### ISSUE THREAD

**Issue by shaicoleman** [rubocop-hq/rubocop#6699]
With the following file:
```
class Example
      private

  def my_method; end
    end
```

When running the following command:
```
$ rubocop --auto-correct --only Layout/IndentationConsistency,Layout/IndentationWidth myfile.rb

Offenses:

myfile.rb:4:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 6) spaces for indentation.
      def my_method; end
^^^^^^
myfile.rb:4:3: C: [Corrected] Layout/IndentationConsistency: Inconsistent indentation detected.
  def my_method; end
  ^^^^^^^^^^^^^^^^^^

0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in /tmp/myfile.rb.
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:270:in `check_for_infinite_loop'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:253:in `block in iterate_until_no_changes'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:252:in `loop'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:252:in `iterate_until_no_changes'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:223:in `do_inspection_loop'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:126:in `block in file_offenses'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:144:in `file_offense_cache'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:124:in `file_offenses'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:112:in `process_file'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:89:in `block in each_inspected_file'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `each'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `reduce'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `each_inspected_file'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:76:in `inspect_files'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:48:in `run'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:174:in `execute_runner'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:75:in `execute_runners'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:47:in `run'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/exe/rubocop:13:in `block in <top (required)>'
/home/shai/.rbenv/versions/2.6.0/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/exe/rubocop:12:in `<top (required)>'
/home/shai/.rbenv/versions/2.6.0/bin/rubocop:23:in `load'
/home/shai/.rbenv/versions/2.6.0/bin/rubocop:23:in `<main>'
```

## RuboCop version
0.63.1 (using Parser 2.5.3.0, running on ruby 2.6.0 x86_64-linux)

Might be related to #6520

**Comment by koic** [comment]
Thanks for the feedback. I opened a PR #6792.
