### ISSUE TITLE
Error occurs for Layout/MultilineMethodCallIndentation

### ISSUE THREAD

**Issue by TimAle** [rubocop-hq/rubocop#6789]
## Expected behavior

Rubocop throws no error messages.

## Actual behavior

```
1 error occurred:
An error occurred while Layout/MultilineMethodCallIndentation cop was inspecting test.rb:1:0.
```

## Steps to reproduce the problem

Create `test.rb` with
```
a[b] { c }
  .d
```

Run
```
rubocop test.rb
```

## RuboCop version
```
0.64.0 (using Parser 2.6.0.0, running on ruby 2.6.1 x86_64-darwin18)
```

**Comment by Drenmi** [comment]
Thanks for the report @TimAle. I was able to reproduce the issue on latest `master`.

Relevant stack trace:

```
undefined method `dot' for #<Parser::Source::Map::Collection:0x00007fa8cd4f0470>
/Users/drenmi/Workspace/RuboCop/rubocop/lib/rubocop/cop/layout/multiline_method_call_indentation.rb:196:in `semantic_alignment_node'
/Users/drenmi/Workspace/RuboCop/rubocop/lib/rubocop/cop/layout/multiline_method_call_indentation.rb:172:in `semantic_alignment_base'
/Users/drenmi/Workspace/RuboCop/rubocop/lib/rubocop/cop/layout/multiline_method_call_indentation.rb:138:in `alignment_base'
/Users/drenmi/Workspace/RuboCop/rubocop/lib/rubocop/cop/layout/multiline_method_call_indentation.rb:78:in `offending_range'
/Users/drenmi/Workspace/RuboCop/rubocop/lib/rubocop/cop/mixin/multiline_expression_indentation.rb:22:in `on_send'
```
