### ISSUE TITLE
lvar parse error

### ISSUE THREAD

**Issue by NatMorcos** [rubocop-hq/rubocop#6809]
Given the following Ruby code

```ruby
name = :name
property(name)
```

and the following node matcher definition

```ruby
def_node_matcher :property_definition?, <<-PATTERN
  (send nil? {:property :property!} ({sym string} _) (hash ...))
PATTERN
```

RuboCop crashes with the following error message:

```
    NoMethodError:
       undefined method `string_type?' for s(:lvar, :name):RuboCop::AST::Node
       Did you mean?  str_type?
     # ./lib/rubocop/cop/shopify/smart_properties_default_values.rb:42:in `property_definition?'
     # ./lib/rubocop/cop/shopify/smart_properties_default_values.rb:21:in `on_send'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/cop/commissioner.rb:58:in `block (2 levels) in trigger_responding_cops'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/cop/commissioner.rb:106:in `with_cop_error_handling'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/cop/commissioner.rb:57:in `block in trigger_responding_cops'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/cop/commissioner.rb:56:in `each'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/cop/commissioner.rb:56:in `trigger_responding_cops'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/cop/commissioner.rb:34:in `block (2 levels) in <class:Commissioner>'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/ast/traversal.rb:50:in `block in on_begin'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/ast/traversal.rb:50:in `each'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/ast/traversal.rb:50:in `on_begin'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/cop/commissioner.rb:35:in `block (2 levels) in <class:Commissioner>'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/ast/traversal.rb:13:in `walk'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/cop/commissioner.rb:46:in `investigate'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/rspec/cop_helper.rb:71:in `_investigate'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/rspec/cop_helper.rb:23:in `inspect_source'
     # /Users/natmorcos/.gem/ruby/2.5.3/gems/rubocop-0.65.0/lib/rubocop/rspec/expect_offense.rb:133:in `expect_no_offenses'
     # ./spec/cops/shopify/smart_properties_default_values_spec.rb:102:in `block (4 levels) in <top (required)>'
```

--------

## Expected behavior

Rubocop successfully parses the line and ignores it given that the first argument is neither a string nor a symbol but actually an expression.

## Actual behavior

Rubocop crashes as outlined above.

## Steps to reproduce the problem

Outlined above.

## RuboCop version

```
$ [bundle exec] rubocop -V
0.65.0 (using Parser 2.6.0.0, running on ruby 2.5.3 x86_64-darwin18)
```

**Comment by Drenmi** [comment]
Hi, @NatMorcos!

Please try changing the `string` fragment in the pattern to `str`. This is the node type as given to us by the parser gem. We currently don't alias `sym` to `symbol` and `str` to `string` (although this makes me think maybe we should.)

```
def_node_matcher :property_definition?, <<-PATTERN
  (send nil? {:property :property!} ({sym str} _) (hash ...))
PATTERN
```

**Comment by NatMorcos** [comment]
🤦‍♂️ ah, yup. Thank you!
