### ISSUE TITLE
uninitialized constant RuboCop::AST::Parser

### ISSUE THREAD

**Issue by dawidof** [rubocop-hq/rubocop#6938]
Trying to execute `rubocop -a` or `rubocop -V` or `bundle exec rubocop -V` 

Receiving an error
```
Traceback (most recent call last):
	10: from /Users/foo/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `<main>'
	 9: from /Users/foo/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `eval'
	 8: from /Users/foo/.rvm/gems/ruby-2.6.2/bin/rubocop:23:in `<main>'
	 7: from /Users/foo/.rvm/gems/ruby-2.6.2/bin/rubocop:23:in `load'
	 6: from /Users/foo/.rvm/gems/ruby-2.6.2/gems/rubocop-0.67.2/exe/rubocop:6:in `<top (required)>'
	 5: from /Users/foo/.rvm/gems/ruby-2.6.2/gems/rubocop-0.67.2/exe/rubocop:6:in `require'
	 4: from /Users/foo/.rvm/gems/ruby-2.6.2/gems/rubocop-0.67.2/lib/rubocop.rb:22:in `<top (required)>'
	 3: from /Users/foo/.rvm/gems/ruby-2.6.2/gems/rubocop-0.67.2/lib/rubocop.rb:22:in `require_relative'
	 2: from /Users/foo/.rvm/gems/ruby-2.6.2/gems/rubocop-0.67.2/lib/rubocop/ast/node.rb:3:in `<top (required)>'
	 1: from /Users/foo/.rvm/gems/ruby-2.6.2/gems/rubocop-0.67.2/lib/rubocop/ast/node.rb:4:in `<module:RuboCop>'
/Users/foo/.rvm/gems/ruby-2.6.2/gems/rubocop-0.67.2/lib/rubocop/ast/node.rb:21:in `<module:AST>': uninitialized constant RuboCop::AST::Parser (NameError)
```

**Comment by koic** [comment]
I didn't know [ruby_executable_hooks](https://github.com/rvm/executable-hooks). So I'm not sure if it would be a hint... How about updating the latest RubyGems with `gem update --system`?

**Comment by koic** [comment]
Or maybe it is related to #6939.

**Comment by dawidof** [comment]
@koic removing `gem 'rubocop-performance'` from Gemfile solved the issue.
Thanks for your help
