### ISSUE TITLE
Problem in Gemfile-less folder

### ISSUE THREAD

**Issue by zverok** [rubocop-hq/rubocop#6939]
In a small folder with only one file (even empty one), attempt to run `rubocop file.rb` now leads to:
```
$ rubocop file.rb
/home/zverok/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:34:in `default_gemfile': Could not locate Gemfile (Bundler::GemfileNotFound)
	from /home/zverok/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:39:in `default_lockfile'
	from /home/zverok/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler.rb:318:in `default_lockfile'
	from /home/zverok/.rvm/gems/ruby-2.4.2/gems/rubocop-0.67.2/exe/rubocop:13:in `<top (required)>'
	from /home/zverok/.rvm/gems/ruby-2.4.2/bin/rubocop:23:in `load'
	from /home/zverok/.rvm/gems/ruby-2.4.2/bin/rubocop:23:in `<main>'
	from /home/zverok/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/zverok/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```
The problem is here: https://github.com/rubocop-hq/rubocop/blob/master/exe/rubocop#L12
Rubocop assumes that if the `Bundler` constant is defined, it should be able to load a Gemfile. It proves to be generally wrong, at least on my system, `Bundler` constant gets defined in RubyGem's `ruby_executable_hooks` executable. 

Environment:
```
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
$ gem -v
2.6.14
$ bundler -v
Bundler version 1.16.1
$ rubocop -V 
# ooops same error...
$ gem which rubocop
/home/zverok/.rvm/gems/ruby-2.4.2/gems/rubocop-0.67.2/lib/rubocop.rb
```

**Comment by koic** [comment]
Thanks for the feedback. I opened a PR #6939.
