### ISSUE TITLE
Error in Layout/EmptyLineAfterGuardClause parsing Ternaries

### ISSUE THREAD

**Issue by natesholland** [rubocop-hq/rubocop#7033]
I discovered a bug that when you run Rubocop 0.68.1 on a file with the following code it will error:

```
def foo
  puts "some action happens here"
rescue  => e
  a_check ? raise(e): other_thing
  true
end
```

This file is about as small as I can make it to reproduce the error.

This is the stack trace it spits out (cleaned my user and rvm stuff out):
```
An error occurred while Layout/EmptyLineAfterGuardClause cop was inspecting /Users/natesholland/code/work/example.rb:4:2.
undefined method `end' for #<Parser::Source::Map::Ternary:0x00007f903121e698>
rubocop-0.68.1/lib/rubocop/cop/layout/empty_line_after_guard_clause.rb:133:in `offense_location'
rubocop-0.68.1/lib/rubocop/cop/layout/empty_line_after_guard_clause.rb:56:in `on_if'
rubocop-0.68.1/lib/rubocop/cop/commissioner.rb:59:in `block (2 levels) in trigger_responding_cops'
rubocop-0.68.1/lib/rubocop/cop/commissioner.rb:130:in `with_cop_error_handling'
rubocop-0.68.1/lib/rubocop/cop/commissioner.rb:58:in `block in trigger_responding_cops'
rubocop-0.68.1/lib/rubocop/cop/commissioner.rb:57:in `each'
rubocop-0.68.1/lib/rubocop/cop/commissioner.rb:57:in `trigger_responding_cops'
rubocop-0.68.1/lib/rubocop/cop/commissioner.rb:34:in `block (2 levels) in <class:Commissioner>'
rubocop-0.68.1/lib/rubocop/ast/traversal.rb:50:in `block in on_begin'
rubocop-0.68.1/lib/rubocop/ast/traversal.rb:50:in `each'
rubocop-0.68.1/lib/rubocop/ast/traversal.rb:50:in `on_begin'
rubocop-0.68.1/lib/rubocop/cop/commissioner.rb:35:in `block (2 levels) in <class:Commissioner>'
rubocop-0.68.1/lib/rubocop/ast/traversal.rb:169:in `block in on_case'
rubocop-0.68.1/lib/rubocop/ast/traversal.rb:168:in `each'
rubocop-0.68.1/lib/rubocop/ast/traversal.rb:168:in `on_case'
rubocop-0.68.1/lib/rubocop/cop/commissioner.rb:35:in `block (2 levels) in <class:Commissioner>'
rubocop-0.68.1/lib/rubocop/ast/traversal.rb:169:in `block in on_case'
rubocop-0.68.1/lib/rubocop/ast/traversal.rb:168:in `each'
rubocop-0.68.1/lib/rubocop/ast/traversal.rb:168:in `on_case'
rubocop-0.68.1/lib/rubocop/cop/commissioner.rb:35:in `block (2 levels) in <class:Commissioner>'
rubocop-0.68.1/lib/rubocop/ast/traversal.rb:100:in `on_def'
rubocop-0.68.1/lib/rubocop/cop/commissioner.rb:35:in `block (2 levels) in <class:Commissioner>'
rubocop-0.68.1/lib/rubocop/ast/traversal.rb:13:in `walk'
rubocop-0.68.1/lib/rubocop/cop/commissioner.rb:46:in `investigate'
rubocop-0.68.1/lib/rubocop/cop/team.rb:116:in `investigate'
rubocop-0.68.1/lib/rubocop/cop/team.rb:104:in `offenses'
rubocop-0.68.1/lib/rubocop/cop/team.rb:44:in `inspect_file'
rubocop-0.68.1/lib/rubocop/runner.rb:273:in `inspect_file'
rubocop-0.68.1/lib/rubocop/runner.rb:220:in `block in do_inspection_loop'
rubocop-0.68.1/lib/rubocop/runner.rb:252:in `block in iterate_until_no_changes'
rubocop-0.68.1/lib/rubocop/runner.rb:245:in `loop'
rubocop-0.68.1/lib/rubocop/runner.rb:245:in `iterate_until_no_changes'
rubocop-0.68.1/lib/rubocop/runner.rb:216:in `do_inspection_loop'
rubocop-0.68.1/lib/rubocop/runner.rb:119:in `block in file_offenses'
rubocop-0.68.1/lib/rubocop/runner.rb:137:in `file_offense_cache'
rubocop-0.68.1/lib/rubocop/runner.rb:117:in `file_offenses'
rubocop-0.68.1/lib/rubocop/runner.rb:105:in `process_file'
rubocop-0.68.1/lib/rubocop/runner.rb:82:in `block in each_inspected_file'
rubocop-0.68.1/lib/rubocop/runner.rb:81:in `each'
rubocop-0.68.1/lib/rubocop/runner.rb:81:in `reduce'
rubocop-0.68.1/lib/rubocop/runner.rb:81:in `each_inspected_file'
rubocop-0.68.1/lib/rubocop/runner.rb:73:in `inspect_files'
rubocop-0.68.1/lib/rubocop/runner.rb:39:in `run'
rubocop-0.68.1/lib/rubocop/cli.rb:210:in `execute_runner'
rubocop-0.68.1/lib/rubocop/cli.rb:80:in `execute_runners'
rubocop-0.68.1/lib/rubocop/cli.rb:51:in `run'
rubocop-0.68.1/exe/rubocop:13:in `block in <top (required)>'
benchmark.rb:308:in `realtime'
rubocop-0.68.1/exe/rubocop:12:in `<top (required)>'
```

## Expected behavior

I would expect it to not throw an error here.

## Actual behavior

The error above happens.

## Steps to reproduce the problem

Here is a script to reproduce the issue.
```
cat << EOF > example.rb
def foo
  puts "some action happens here"
rescue  => e
  a_check ? raise(e): other_thing
  true
end
EOF
rubocop -d example.rb
```

## RuboCop version

`0.68.1`

**Comment by natesholland** [comment]
It looks like @koic and @bbatsov may have already fixed this in this commit

https://github.com/rubocop-hq/rubocop/commit/4910d514e1#diff-1681d32b641581525ec5917b802ef152R133

But it will need to be released to address this issue.

**Comment by koic** [comment]
Thanks for the feedback. The above commit did not solve it. I opened a PR #7034.

**Comment by natesholland** [comment]
Ahh, yea I should have realized that. Thanks for the fix.
