### ISSUE TITLE
Crash when having ~/.rubocop.yml file requiring extension

### ISSUE THREAD

**Issue by vfonic** [rubocop-hq/rubocop#7132]
My `~/.rubocop.yml` requires `rubocop-rails`. However, when I tried to run `bundle exec rake default` (essentially rubocop) in rubocop git repo's root, I received the following error:

```sh
$ bundle exec rake default
Running RuboCop...
cannot load such file -- rubocop-rails
/Users/viktor/Developer/gems/rubocop/lib/rubocop/config_loader_resolver.rb:15:in `require'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/config_loader_resolver.rb:11:in `each'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/config_loader.rb:45:in `load_file'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/config_loader.rb:107:in `add_excludes_from_files'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/config_loader.rb:92:in `configuration_from_file'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/config_store.rb:44:in `for'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/cli.rb:180:in `validate_options_vs_config'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/cli.rb:48:in `run'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/rake_task.rb:44:in `run_cli'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/rake_task.rb:28:in `block (2 levels) in initialize'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/file_utils_ext.rb:59:in `verbose'
/Users/viktor/Developer/gems/rubocop/lib/rubocop/rake_task.rb:26:in `block in initialize'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/Users/viktor/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/viktor/.rvm/rubies/ruby-2.6.3/bin/rake:23:in `load'
/Users/viktor/.rvm/rubies/ruby-2.6.3/bin/rake:23:in `<main>'
/Users/viktor/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/viktor/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
RuboCop failed!
```

## Steps to reproduce the problem

```sh
mv ~/.rubocop.yml ~/.rubocop.yml_bak # backup your rubocop config if any
echo "require: 'rubocop-rails'" > ~/.rubocop.yml
rubocop # or bundle exec rake default, depending where you are
```

Since rubocop repo has its own `.rubocop.yml`, the `~/.rubocop.yml` in my home directory should be completely ignored.

This makes it really hard to work on any project that doesn't have `rubocop-rails` as a dependency, even if it has its own `.rubocop.yml` config file.

## RuboCop version

```
$ [bundle exec] rubocop -V
0.71.0 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-darwin18)
```

**Comment by tejasbubane** [comment]
Same as https://github.com/rubocop-hq/rubocop/issues/7032.

**Comment by vfonic** [comment]
Indeed, I think the underlying issue is the same. I'll c/p my post over there.
