### ISSUE TITLE
Infinite loop in Style/FrozenStringLiteralComment

### ISSUE THREAD

**Issue by deepj** [rubocop-hq/rubocop#7586]
I just tried applying Rubocop autocorrect rules on one of old applications and I got infinite loop in ` Style/FrozenStringLiteralComment` rule in a script. The problematic code is below. I know it's a bit incorrect usage of `coding` magic comment but the script wasn't written by me. On the other hand I consider this error as a bug in this case though. 
 
## Expected behavior

Autocorrect is without infinite loop

## Actual behavior

Infinite loop detected in the code below

## Steps to reproduce the problem

```
#! bin/rails runner

# coding: utf-8

puts 'DEPRECATED!'
exit
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.78.0 (using Parser 2.6.5.0, running on ruby 2.6.5 x86_64-darwin18)
```

**Comment by pirj** [comment]
Can't reproduce on 2.5.5 or 2.7.0 (didn't try on 2.6.5).
Are you certain that infinite loop is in `FrozenStringLiteralComment`?
Does it reproduce on your side when you run:
```
rubocop --only Style/FrozenStringLiteralComment that_file.rb
```
Can you provide a backtrace or the output with `--debug`?

**Comment by buehmann** [comment]
@pirj I get this with the input file from above on rubocop master (using Parser 2.6.5.0, running on ruby 2.7.0 x86_64-linux):
```
Inspecting 1 file
C

Offenses:

tmp-7586.rb:1:1: C: [Corrected] Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
#! bin/rails runner ruby
^

0 files inspected, 1 offense detected, 1 offense corrected
Infinite loop detected in /home/buehmann/dev/rubocop/tmp-7586.rb.
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:273:in `block in iterate_until_no_changes'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:269:in `loop'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:269:in `iterate_until_no_changes'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:240:in `do_inspection_loop'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:119:in `block in file_offenses'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:143:in `file_offense_cache'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:117:in `file_offenses'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:108:in `process_file'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:86:in `each'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:86:in `reduce'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:86:in `each_inspected_file'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:73:in `inspect_files'
/home/buehmann/dev/rubocop/lib/rubocop/runner.rb:39:in `run'
/home/buehmann/dev/rubocop/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/home/buehmann/dev/rubocop/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/home/buehmann/dev/rubocop/lib/rubocop/cli/command.rb:10:in `run'
/home/buehmann/dev/rubocop/lib/rubocop/cli/environment.rb:17:in `run'
/home/buehmann/dev/rubocop/lib/rubocop/cli.rb:65:in `run_command'
/home/buehmann/dev/rubocop/lib/rubocop/cli.rb:72:in `execute_runners'
/home/buehmann/dev/rubocop/lib/rubocop/cli.rb:41:in `run'
/home/buehmann/dev/rubocop/exe/rubocop:13:in `block in <top (required)>'
/home/buehmann/.rbenv/versions/2.7.0/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/home/buehmann/dev/rubocop/exe/rubocop:12:in `<top (required)>'
/home/buehmann/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bin/rubocop:23:in `load'
/home/buehmann/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bin/rubocop:23:in `<main>'
```
Input file looks like this when the loop is aborted:
```ruby
#! bin/rails runner ruby

# coding: utf-8
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true
# frozen_string_literal: true

puts 'DEPRECATED!'
exit
```
