### ISSUE TITLE
Crash with `invalid byte sequence in UTF-8` error

### ISSUE THREAD

**Issue by tas50** [rubocop-hq/rubocop#7848]
## Expected behavior

If ruby file contains invalid UTF character rubocop should either skip the file or throw an error that tells you what file has the issue.

## Actual behavior

RuboCop will throw the following error without indicating which file failed to parse which makes these a bit tricky to track down with large codebases.

```
Inspecting 1 file
.

0 files inspected, no offenses detected
invalid byte sequence in UTF-8
/usr/local/lib/ruby/gems/2.7.0/gems/parser-2.7.1.0/lib/parser/source/buffer.rb:166:in `source='
/Users/tsmith/dev/oss/rubocop/lib/rubocop/cached_data.rb:47:in `deserialize_offenses'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/cached_data.rb:13:in `from_json'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/result_cache.rb:96:in `load'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/runner.rb:133:in `file_offense_cache'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/runner.rb:117:in `file_offenses'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/runner.rb:108:in `process_file'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/runner.rb:86:in `each'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/runner.rb:86:in `reduce'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/runner.rb:86:in `each_inspected_file'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/runner.rb:73:in `inspect_files'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/runner.rb:39:in `run'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/cli/command.rb:10:in `run'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/cli/environment.rb:17:in `run'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/cli.rb:65:in `run_command'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/cli.rb:72:in `execute_runners'
/Users/tsmith/dev/oss/rubocop/lib/rubocop/cli.rb:41:in `run'
/Users/tsmith/dev/oss/rubocop/exe/rubocop:13:in `block in <top (required)>'
/usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/Users/tsmith/dev/oss/rubocop/exe/rubocop:12:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/bin/rubocop:23:in `load'
/usr/local/lib/ruby/gems/2.7.0/bin/rubocop:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/opt/ruby/bin/bundle:23:in `load'
/usr/local/opt/ruby/bin/bundle:23:in `<main>'
```

## Steps to reproduce the problem

Since I can't just paste the file in here's the source I'm trying to scan:

<https://supermarket.chef.io/cookbooks/bind9-chroot/download>

the file with the invalid character is at `libraries/nameserver_proxy.rb`

## RuboCop version

master:

```
0.81.0 (using Parser 2.7.1.0, running on ruby 2.7.1 x86_64-darwin19)
```

**Comment by koic** [comment]
Ruby's default script encoding is UTF-8. OTOH, the file encoding seems to be Shift_JIS instead of UTF-8.

```console
% nkf --guess nameserver_proxy.rb
Shift_JIS (LF)
```

A solution would be to convert the file encoding to UTF-8. Below is a example.

```console
% nkf -w --overwrite nameserver_proxy.rb
% nkf --guess nameserver_proxy.rb
UTF-8 (LF)
```

Or specify Shift_JIS in the magic comment.

```diff
diff --git a/7848/nameserver_proxy.rb b/7848/nameserver_proxy.rb
index 0059a31..a27d37f 100644
--- a/7848/nameserver_proxy.rb
+++ b/7848/nameserver_proxy.rb
@@ -1,3 +1,5 @@
+# encoding: Shift_JIS
+
 module LeCafeAutomatique
   module Bind9
     module NameServer
```

Either way, matching the script and file encodings will solve the issue.

**Comment by tas50** [comment]
Closing based on the feedback.
