### ISSUE TITLE
Error: `bad value for range` error in Lint/SuppressedException cop

### ISSUE THREAD

**Issue by filipkis** [rubocop-hq/rubocop#8089]
I'm getting an error for `Lint/SuppressedException` cop when there are two rescue blocks one after another an the first one is suppressed (either has nothing in or has only a comment).

--------

## Expected behavior

There should be no error.

## Actual behavior

I'm getting the following error

```
An error occurred while Lint/SuppressedException cop was inspecting /path/to/my/file.rb.
bad value for range
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/lint/suppressed_exception.rb:85:in `comment_between_rescue_and_end?'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/lint/suppressed_exception.rb:72:in `on_resbody'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/commissioner.rb:136:in `with_cop_error_handling'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/commissioner.rb:55:in `each'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/commissioner.rb:32:in `block (2 levels) in <class:Commissioner>'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-ast-0.0.3/lib/rubocop/ast/traversal.rb:176:in `block in on_case'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-ast-0.0.3/lib/rubocop/ast/traversal.rb:175:in `each'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-ast-0.0.3/lib/rubocop/ast/traversal.rb:175:in `on_case'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-ast-0.0.3/lib/rubocop/ast/traversal.rb:107:in `on_def'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-ast-0.0.3/lib/rubocop/ast/traversal.rb:14:in `walk'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/commissioner.rb:44:in `investigate'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/team.rb:124:in `investigate'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/team.rb:112:in `offenses'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:295:in `inspect_file'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:245:in `block in do_inspection_loop'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:277:in `block in iterate_until_no_changes'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:270:in `loop'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:270:in `iterate_until_no_changes'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:241:in `do_inspection_loop'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:122:in `block in file_offenses'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:146:in `file_offense_cache'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:120:in `file_offenses'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:111:in `process_file'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:90:in `block in each_inspected_file'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:89:in `each'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:89:in `reduce'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:89:in `each_inspected_file'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:78:in `inspect_files'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/runner.rb:39:in `run'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cli/command.rb:10:in `run'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cli/environment.rb:17:in `run'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cli.rb:65:in `run_command'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cli.rb:72:in `execute_runners'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/lib/rubocop/cli.rb:41:in `run'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/exe/rubocop:13:in `block in <top (required)>'
/Path/.rbenv/versions/2.5.5/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/Path/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.84.0/exe/rubocop:12:in `<top (required)>'
/Path/.rbenv/versions/2.5.5/bin/rubocop:23:in `load'
/Path/.rbenv/versions/2.5.5/bin/rubocop:23:in `<main>'
```

## Steps to reproduce the problem

The minimal example that causes the error

```ruby
def test
rescue StandardError
  # Comment
rescue Error
  false
end
```

## RuboCop version

```
$ bundle exec rubocop -V
0.84.0 (using Parser 2.7.1.2, rubocop-ast 0.0.3, running on ruby 2.5.5 x86_64-darwin18)
```

**Comment by koic** [comment]
This issue has been resolved by #8010. Can you update to RuboCop 0.85.0? Thank you.
