### ISSUE TITLE
Rubocop not working anymore with Ruby v2.7.1

### ISSUE THREAD

**Issue by imtiazwazir** [rubocop-hq/rubocop#8190]
It used to work two or three weeks back but now when I run just `rubocop` command from project directory it spit our following error.

```
Traceback (most recent call last):
	15: from /Users/abc/.rvm/gems/ruby-2.7.1/bin/rubocop:23:in `<main>'
	14: from /Users/abc/.rvm/gems/ruby-2.7.1/bin/rubocop:23:in `load'
	13: from /Users/abc/.rvm/gems/ruby-2.7.1/gems/rubocop-0.86.0/exe/rubocop:6:in `<top (required)>'
	12: from /Users/abc/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	11: from /Users/abc/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	10: from /Users/abc/.rvm/gems/ruby-2.7.1/gems/rubocop-0.86.0/lib/rubocop.rb:10:in `<top (required)>'
	 9: from /Users/abc/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 8: from /Users/abc/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 7: from /Users/abc/.rvm/gems/ruby-2.7.1/gems/rubocop-ast-0.0.3/lib/rubocop-ast.rb:3:in `<top (required)>'
	 6: from /Users/abc/.rvm/gems/ruby-2.7.1/gems/rubocop-ast-0.0.3/lib/rubocop-ast.rb:3:in `require_relative'
	 5: from /Users/abc/.rvm/gems/ruby-2.7.1/gems/rubocop-ast-0.0.3/lib/rubocop/ast.rb:3:in `<top (required)>'
	 4: from /Users/abc/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /Users/abc/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 2: from /Users/abc/.rvm/gems/ruby-2.7.1/gems/parser-2.7.1.3/lib/parser.rb:14:in `<top (required)>'
	 1: from /Users/abc/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/abc/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- ast (LoadError)
```

By the way with ruby v2.7.0 its working fine.

**Comment by marcandre** [comment]
Strange.

Looks like the `ast` gem (which is the only dependency of `parser`) isn't installed (what does `gem which ast` do?)

Could you try installing the `ast` gem or reinstalling the `parser` gem?

**Comment by imtiazwazir** [comment]
I can confirm, command `gem install ast` fixed the issue.

Thanks!
