### ISSUE TITLE
Error start the application after gems alphabetically sorted

### ISSUE THREAD

**Issue by EnziinSystem** [rubocop-hq/rubocop#8207]
My environment:
```
bash-5.0# rubocop -V
0.80.1 (using Parser 2.7.1.4, running on ruby 2.7.1 x86_64-linux-musl)
bash-5.0# ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
bash-5.0# rails -v
Rails 6.0.3.2
```
In the Gemfile:
```
gem 'activeadmin', '~> 2.7'
gem 'active_admin-sortable_tree', '~> 2.1'
```
I start the Puma server, my application working normally.
Now, I sort gems by alphabetically and Gemfile become:
```
gem 'active_admin-sortable_tree', '~> 2.1'
gem 'activeadmin', '~> 2.7'
```
I start the Puma, oops, it' error because gem 'active_admin-sortable_tree' need gem 'activeadmin' loaded.

In general, gem B depends on Gem A. If the order loaded change by RuboCop then it raises an error.

We can not be known anything about the order load gems depends on themself in an application.

The next version of Rubocop, please remove the method sort Gems by A-Z as below.

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Bundler/OrderedGems

```
Puma starting in single mode...
* Version 4.3.5 (ruby 2.7.1-p83), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: development
! Unable to load application: NameError: uninitialized constant ActiveAdmin
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
NameError: uninitialized constant ActiveAdmin
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
  /usr/local/bundle/gems/active_admin-sortable_tree-2.1.0/lib/active_admin/sortable_tree/compatibility.rb:1:in `<main>'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  /usr/local/bundle/gems/active_admin-sortable_tree-2.1.0/lib/active_admin/sortable_tree.rb:1:in `<main>'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:88:in `rescue in block in require'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:65:in `block in require'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
  /usr/local/lib/ruby/2.7.0/bundler.rb:174:in `require'
  /home/config/application.rb:8:in `<top (required)>'
```

**Comment by marcandre** [comment]
I'd file a bug with `active_admin-sortable_tree`: they should be doing the `require 'active_admin'`

**Comment by EnziinSystem** [comment]
> > In general, gem B depends on Gem A
> 
> Yes, but that is stated in each gem's manifest. gem B is responsible for requiring gem A.
> 
> I'd file a bug with `active_admin-sortable_tree`: they should be doing the `require 'active_admin'`

I known require it, but a program don't raise an error because sorted gems A-Z only.
When we use RuboCop, our code more than beautiful, but not have any errors.

**Comment by marcandre** [comment]
I [did it for you](https://github.com/zorab47/active_admin-sortable_tree/pull/90)

We should consider sorting after removing all the `-` and `_` though. Creating #8209

**Comment by EnziinSystem** [comment]
> I [did it for you](https://github.com/zorab47/active_admin-sortable_tree/pull/90)
> 
> We should consider sorting after removing all the `-` and `_` though. Creating #8209

Thank you!

**Comment by marcandre** [comment]
Future versions will sort ignoring `-` and `_` so this should also resolve this for you. Thanks for raising this issue 😄
