### ISSUE TITLE
Style/CaseLikeIf: undefined method `literal?' for nil:NilClass

### ISSUE THREAD

**Issue by leoarnold** [rubocop-hq/rubocop#8344]
## Expected behavior

Run without exception on sample file

```ruby
module InstanceMethods
  # Returns true if both instances have the same class and identical attributes
  def ==(other)
    if equal?(other)
      true
    elsif other.instance_of?(self.class)
      keys = self.class.attributes.keys
      attributes.values_at(*keys) == other.attributes.values_at(*keys)
    else
      false
    end
  end
end
```

## Actual behavior

```
$ rubocop -d test.rb 
For /home/user/Code/project: configuration from /home/user/Code/project/.rubocop.yml
configuration from /home/user/.rvm/gems/ruby-2.6.6@project/gems/rubocop-performance-1.7.0/config/default.yml
configuration from /home/user/.rvm/gems/ruby-2.6.6@project/gems/rubocop-performance-1.7.0/config/default.yml
Default configuration from /home/user/.rvm/gems/ruby-2.6.6@project/gems/rubocop-0.88.0/config/default.yml
configuration from /home/user/.rvm/gems/ruby-2.6.6@project/gems/rubocop-rspec-1.42.0/config/default.yml
configuration from /home/user/.rvm/gems/ruby-2.6.6@project/gems/rubocop-rspec-1.42.0/config/default.yml
Inspecting 1 file
Scanning /home/user/Code/project/test.rb
An error occurred while Style/CaseLikeIf cop was inspecting /home/user/Code/project/test.rb:4:4.
undefined method `literal?' for nil:NilClass
/home/user/.rvm/gems/ruby-2.6.6@project/gems/rubocop-0.88.0/lib/rubocop/cop/style/case_like_if.rb:118:in `find_target_in_equality_node'
/home/user/.rvm/gems/ruby-2.6.6@project/gems/rubocop-0.88.0/lib/rubocop/cop/style/case_like_if.rb:101:in `find_target_in_send_node'
/home/user/.rvm/gems/ruby-2.6.6@project/gems/rubocop-0.88.0/lib/rubocop/cop/style/case_like_if.rb:91:in `find_target'
/home/user/.rvm/gems/ruby-2.6.6@project/gems/rubocop-0.88.0/lib/rubocop/cop/style/case_like_if.rb:37:in `on_if'
[...]
```

## Steps to reproduce the problem

See above for command and gem versions

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ rubocop -V
0.88.0 (using Parser 2.7.1.4, rubocop-ast 0.1.0, running on ruby 2.6.6 x86_64-linux)
```

**Comment by bbatsov** [comment]
Looks like a task for @fatkodima.
