### ISSUE TITLE
Issue using `Exclude` for `Style/BlockDelimiters`

### ISSUE THREAD

**Issue by lavabyrd** [rubocop-hq/rubocop#8530]
## Expected behavior

I've added the following as I want to exclude `Style/BlockDelimiters` from running on one sub-directory. I expect it to not run on these files.

```
Style/BlockDelimiters:
  Exclude: app/services/item/queries/graph/*.rb
```

## Actual behavior

Each time I run `rubocop -c config/rubocop.yml`, it exits instantly with the following Stacktrace. I've also tried naming the file directly but each time I run `rubocop -c config/rubocop.yml`, I get an instant error. I've removed this cop from my config (and kept the cop and it runs successfully, adding an exclude causes it to fail.

```
undefined method `map!' for "app/services/item/queries/graph/*.rb":String
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.88.0/lib/rubocop/config.rb:73:in `block in make_excludes_absolute'
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/2.6.0/forwardable.rb:230:in `each_key'
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/2.6.0/forwardable.rb:230:in `each_key'
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.88.0/lib/rubocop/config.rb:69:in `make_excludes_absolute'
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.88.0/lib/rubocop/config.rb:45:in `check'
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.88.0/lib/rubocop/config.rb:37:in `create'
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.88.0/lib/rubocop/config_loader.rb:53:in `load_file'
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.88.0/lib/rubocop/config_store.rb:23:in `options_config='
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.88.0/lib/rubocop/cli.rb:88:in `act_on_options'
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.88.0/lib/rubocop/cli.rb:38:in `run'
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.88.0/exe/rubocop:13:in `block in <top (required)>'
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Users/markpreston/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.88.0/exe/rubocop:12:in `<top (required)>'
/Users/markpreston/.rbenv/versions/2.6.6/bin/rubocop:23:in `load'
/Users/markpreston/.rbenv/versions/2.6.6/bin/rubocop:23:in `<main>'
```

## Steps to reproduce the problem

Run `rubocop -c config/rubocop.yml` with the following:

```
Style/BlockDelimiters:
  Exclude: app/services/item/queries/graph/*.rb
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.88.0 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.6.6 x86_64-darwin19)
```

**Comment by lavabyrd** [comment]
Failure on my behalf, bad formatting in my rubocop.yml, it was fixed with 

```
Exclude:
  -  app/....
```
