### ISSUE TITLE
Crasher in LineLength

### ISSUE THREAD

**Issue by kwerle** [rubocop-hq/rubocop#8587]
LineLength is crashing on the line:
```
Rails.application.config.content_security_policy_nonce_generator = -> _request { SecureRandom.base64(16) }
```

In an empty directory, create test.rb file with that line.
Run rubocop
Boom
Sad panda

Full output from rubocop -d with no configuration options at all:

```
root@dea54bf4d322:/tmp/x# rubocop -d
For /tmp/x: configuration from /usr/local/bundle/gems/rubocop-0.80.0/config/default.yml
Inspecting 1 file
Scanning /tmp/x/test.rb
An error occurred while Layout/LineLength cop was inspecting /tmp/x/test.rb:1:67.
undefined method `begin_pos' for nil:NilClass
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/layout/line_length.rb:127:in `check_for_breakable_block'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/layout/line_length.rb:71:in `on_block'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/commissioner.rb:136:in `with_cop_error_handling'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/commissioner.rb:55:in `each'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/commissioner.rb:32:in `block (2 levels) in <class:Commissioner>'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/ast/traversal.rb:114:in `block in on_send'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/ast/traversal.rb:111:in `each'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/ast/traversal.rb:111:in `each_with_index'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/ast/traversal.rb:111:in `on_send'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/ast/traversal.rb:14:in `walk'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/commissioner.rb:44:in `investigate'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/team.rb:124:in `investigate'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/team.rb:112:in `offenses'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:296:in `inspect_file'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:244:in `block in do_inspection_loop'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:276:in `block in iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:269:in `loop'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:269:in `iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:240:in `do_inspection_loop'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:119:in `block in file_offenses'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:143:in `file_offense_cache'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:117:in `file_offenses'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:108:in `process_file'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:86:in `each'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:86:in `reduce'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:86:in `each_inspected_file'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:73:in `inspect_files'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/runner.rb:39:in `run'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cli/command.rb:10:in `run'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cli/environment.rb:17:in `run'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cli.rb:65:in `run_command'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cli.rb:72:in `execute_runners'
/usr/local/bundle/gems/rubocop-0.80.0/lib/rubocop/cli.rb:41:in `run'
/usr/local/bundle/gems/rubocop-0.80.0/exe/rubocop:13:in `block in <top (required)>'
/usr/local/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/gems/rubocop-0.80.0/exe/rubocop:12:in `<top (required)>'
/usr/local/bundle/bin/rubocop:23:in `load'
/usr/local/bundle/bin/rubocop:23:in `<main>'
C

Offenses:

test.rb:1:1: C: Style/FrozenStringLiteralComment: Missing frozen string literal comment.
Rails.application.config.content_security_policy_nonce_generator = -> _request { SecureRandom.base64(16) }
^
test.rb:1:68: C: Layout/SpaceInLambdaLiteral: Do not use spaces between -> and ( in lambda literals.
Rails.application.config.content_security_policy_nonce_generator = -> _request { SecureRandom.base64(16) }
                                                                   ^^^^^^^^^^^
test.rb:1:71: C: Style/StabbyLambdaParentheses: Wrap stabby lambda arguments with parentheses.
Rails.application.config.content_security_policy_nonce_generator = -> _request { SecureRandom.base64(16) }
                                                                      ^^^^^^^^
test.rb:1:81: C: Layout/LineLength: Line is too long. [106/80]
Rails.application.config.content_security_policy_nonce_generator = -> _request { SecureRandom.base64(16) }
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 4 offenses detected

1 error occurred:
An error occurred while Layout/LineLength cop was inspecting /tmp/x/test.rb:1:67.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.80.0 (using Parser 2.7.0.3, running on ruby 2.5.8 x86_64-linux)
Finished in 0.12318919999961508 seconds
root@dea54bf4d322:/tmp/x# 

```

**Comment by koic** [comment]
> 0.80.0 (using Parser 2.7.0.3, running on ruby 2.5.8 x86_64-linux)

This issue has not reproduced with RuboCop 0.89.1. Can you upgrade to the latest RuboCop?

**Comment by kwerle** [comment]
I was able to update as far as 0.84.0.
It no longer reproduces.  Thanks!

**Comment by koic** [comment]
You are welcome!
