### ISSUE TITLE
TypeError while Metrics/AbcSize on `self::Constant ||= something`

### ISSUE THREAD

**Issue by Tietew** [rubocop-hq/rubocop#8742]
### test.rb

``` ruby
def foo
  self::FooModule ||= Module.new
end
```

Note: same error when `Object::FooModule ||=`

### Run rubocop

```
$ bundle exec rubocop -d --only Metrics/AbcSize test.rb
(snip)
Inspecting 1 file
Scanning .../test.rb
An error occurred while Metrics/AbcSize cop was inspecting .../test.rb:1:0.
no implicit conversion of RuboCop::AST::Node into String
.../rubocop-0.91.0/lib/rubocop/cop/metrics/utils/abc_size_calculator.rb:102:in `match?'
.../rubocop-0.91.0/lib/rubocop/cop/metrics/utils/abc_size_calculator.rb:102:in `capturing_variable?'
.../rubocop-0.91.0/lib/rubocop/cop/metrics/utils/abc_size_calculator.rb:87:in `assignment?'
.../rubocop-0.91.0/lib/rubocop/cop/metrics/utils/abc_size_calculator.rb:46:in `block in calculate'
.../rubocop-ast-0.4.1/lib/rubocop/ast/node.rb:626:in `block in visit_descendants'
(snip)
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Metrics/AbcSize cop was inspecting .../test.rb:1:0.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.91.0 (using Parser 2.7.1.4, rubocop-ast 0.4.1, running on ruby 2.6.6 x86_64-linux)
Finished in 0.09263256285339594 seconds
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.91.0 (using Parser 2.7.1.4, rubocop-ast 0.4.1, running on ruby 2.6.6 x86_64-linux)
```

**Comment by marcandre** [comment]
I'll handle this, just need a bit more time as I realize there are a few other issues...

**Comment by marcandre** [comment]
Fixed, along with a few tweaks to the metric. Thanks for opening this issue.
