### ISSUE TITLE
pronto-rubocop breaking "undefined method `corrections'"

### ISSUE THREAD

**Issue by alexhouse** [rubocop-hq/rubocop#8858]
After a bit of an ignored hiatus we're trying to get pronto running again on one of our projects, including pronto-rubocop. It seems with recent updates (around June?) that pronto-rubocop hasn't been up dated to handle the latest version yet as we're getting the following error when running it:

```sh
undefined method `corrections' for #<RuboCop::Cop::Corrector:0x00007fd594a4d758> (NoMethodError)
```

Full trace:

```sh
❯ bundle exec pronto run -c origin/master -r rubocop -f text
Traceback (most recent call last):
  30: from $HOME/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'
	29: from $HOME/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'
	28: from $HOME/.rvm/gems/ruby-2.7.1/bin/pronto:23:in `<main>'
27: from $HOME/.rvm/gems/ruby-2.7.1/bin/pronto:23:in `load'
	26: from $HOME/.rvm/gems/ruby-2.7.1/gems/pronto-0.10.0/bin/pronto:6:in `<top (required)>'
	25: from $HOME/.rvm/gems/ruby-2.7.1/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
24: from $HOME/.rvm/gems/ruby-2.7.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	23: from $HOME/.rvm/gems/ruby-2.7.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	22: from $HOME/.rvm/gems/ruby-2.7.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
21: from $HOME/.rvm/gems/ruby-2.7.1/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `run'
	20: from $HOME/.rvm/gems/ruby-2.7.1/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `chdir'
	19: from $HOME/.rvm/gems/ruby-2.7.1/gems/pronto-0.10.0/lib/pronto/cli.rb:66:in `block in run'
18: from $HOME/.rvm/gems/ruby-2.7.1/gems/pronto-0.10.0/lib/pronto.rb:64:in `run'
	17: from $HOME/.rvm/gems/ruby-2.7.1/gems/pronto-0.10.0/lib/pronto/runners.rb:13:in `run'
	16: from $HOME/.rvm/gems/ruby-2.7.1/gems/pronto-0.10.0/lib/pronto/runners.rb:13:in `each'
15: from $HOME/.rvm/gems/ruby-2.7.1/gems/pronto-0.10.0/lib/pronto/runners.rb:20:in `block in run'
	14: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop.rb:11:in `run'
	13: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop.rb:11:in `flat_map'
12: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop.rb:11:in `each'
	11: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop.rb:11:in `block in run'
	10: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop/patch_cop.rb:14:in `messages'
9: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop/patch_cop.rb:14:in `flat_map'
	 8: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop/patch_cop.rb:14:in `each'
	 7: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop/patch_cop.rb:18:in `block in messages'
6: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop/patch_cop.rb:18:in `map'
	 5: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop/patch_cop.rb:18:in `block (2 levels) in messages'
	 4: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop/offense_line.rb:11:in `message'
3: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop/offense_line.rb:27:in `message_text'
	 2: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop/offense_line.rb:34:in `suggestion_text'
	 1: from $HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop/offense_line.rb:45:in `corrections_count'
$HOME/.rvm/gems/ruby-2.7.1/bundler/gems/pronto-rubocop-dd3c6126d766/lib/pronto/rubocop/offense_line.rb:86:in `corrector': undefined method `corrections' for #<RuboCop::Cop::Corrector:0x00007fd594a4d758> (NoMethodError)
```

I expect this is better posted to pronto-rubocop repo but thought it worth raising here too.

--------

## Expected behavior

Pronto runs rubocop

## Actual behavior

Pronto rubocop fails

## Steps to reproduce the problem

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

## RuboCop version

```
0.92.0 (using Parser 2.7.2.0, rubocop-ast 0.7.1, running on ruby 2.7.1 x86_64-darwin19)
```

Pronto version

```
0.10.0 (running on ruby 2.7.1 x86_64-darwin19)
```

`pronto-rubocop` version

```
pronto-rubocop (0.10.0 dd3c612)
```

**Comment by marcandre** [comment]
I'm sorry about the issues you're having.

Thanks for the full stacktrace, glad to see you are using the latest `pronto-rubocop` 👍

I knew some changes were breaking [and offered my help](https://github.com/prontolabs/pronto-rubocop/issues/50) but I'm still waiting to hear back. The project doesn't look very active 😿.

There won't be changes on our end, so could you please open an issue over there (feel free to tag me)?

**Comment by alexhouse** [comment]
Of course, figured it was worth a shot raising here since - as you say - `pronto-rubocop` is a bit...dead!

Thanks for the reply :+1:

**Comment by marcandre** [comment]
I might have a look anyways; if their specs are already failing, and if you can try out a fork it might work.

**Comment by alexhouse** [comment]
that would be awesome, thank you very much. Happy to help in any way we can.
