### ISSUE TITLE
Crash with Layout/SpaceAroundMethodCallOperator cop

### ISSUE THREAD

**Issue by mjobin-mdsol** [rubocop-hq/rubocop#8952]
Getting errors which suggest a bug in rubocop with an invitation to submit a report.
first time I see this. 0.88

## Expected behavior

rubocop should run without errors.

## Actual behavior

I see errors

## Steps to reproduce the problem

```
$ rubocop --only Layout/SpaceAroundMethodCallOperator app/views/api/v3/platform_identifiers/show.json.jbuilder -d
For /Users/majobin/code/proj: configuration from /Users/majobin/code/iproj/.rubocop.yml
Inheriting .rubocop_todo.yml:365: `Layout/LineLength` is concealed by line 2117
configuration from /Users/majobin/code/iproj/.rubocop_todo.yml
Default configuration from /Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/config/default.yml

The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Lint/DuplicateElsifCondition (0.88)
 - Lint/MixedRegexpCaptureTypes (0.85)
 - Style/AccessorGrouping (0.87)
 - Style/ArrayCoercion (0.88)
 - Style/BisectedAttrAccessor (0.87)
 - Style/CaseLikeIf (0.88)
 - Style/HashAsLastArrayItem (0.88)
 - Style/HashLikeCase (0.88)
 - Style/RedundantAssignment (0.87)
 - Style/RedundantFetchBlock (0.86)
 - Style/RedundantFileExtensionInRequire (0.88)
 - Style/RedundantRegexpCharacterClass (0.85)
 - Style/RedundantRegexpEscape (0.85)
For more information: https://docs.rubocop.org/rubocop/versioning.html
Inspecting 1 file
Scanning /Users/majobin/code/iproj/app/views/api/v3/platform_identifiers/show.json.jbuilder
An error occurred while Layout/SpaceAroundMethodCallOperator cop was inspecting /Users/majobin/code/iproj/app/views/api/v3/platform_identifiers/show.json.jbuilder:6:4.
undefined method `begin_pos' for nil:NilClass
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/layout/space_around_method_call_operator.rb:69:in `check_space_after_dot'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/layout/space_around_method_call_operator.rb:49:in `on_send'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/commissioner.rb:91:in `block (2 levels) in trigger_responding_cops'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/commissioner.rb:113:in `with_cop_error_handling'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/commissioner.rb:90:in `block in trigger_responding_cops'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/commissioner.rb:89:in `each'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/commissioner.rb:89:in `trigger_responding_cops'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/commissioner.rb:61:in `block (2 levels) in <class:Commissioner>'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-ast-0.2.0/lib/rubocop/ast/traversal.rb:173:in `on_block'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/commissioner.rb:62:in `block (2 levels) in <class:Commissioner>'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-ast-0.2.0/lib/rubocop/ast/traversal.rb:59:in `block in on_begin'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-ast-0.2.0/lib/rubocop/ast/traversal.rb:59:in `each'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-ast-0.2.0/lib/rubocop/ast/traversal.rb:59:in `on_begin'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/commissioner.rb:62:in `block (2 levels) in <class:Commissioner>'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-ast-0.2.0/lib/rubocop/ast/traversal.rb:173:in `on_block'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/commissioner.rb:62:in `block (2 levels) in <class:Commissioner>'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-ast-0.2.0/lib/rubocop/ast/traversal.rb:14:in `walk'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/commissioner.rb:74:in `investigate'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/team.rb:151:in `investigate_partial'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cop/team.rb:83:in `investigate'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:295:in `inspect_file'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:245:in `block in do_inspection_loop'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:277:in `block in iterate_until_no_changes'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:270:in `loop'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:270:in `iterate_until_no_changes'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:241:in `do_inspection_loop'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:121:in `block in file_offenses'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:146:in `file_offense_cache'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:120:in `file_offenses'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:111:in `process_file'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:90:in `block in each_inspected_file'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:89:in `each'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:89:in `reduce'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:89:in `each_inspected_file'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:78:in `inspect_files'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/runner.rb:39:in `run'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cli/command.rb:10:in `run'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cli/environment.rb:17:in `run'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cli.rb:65:in `run_command'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cli.rb:72:in `execute_runners'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/lib/rubocop/cli.rb:41:in `run'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/exe/rubocop:13:in `block in <top (required)>'
/Users/majobin/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/Users/majobin/.rvm/gems/ruby-2.5.8/gems/rubocop-0.88.0/exe/rubocop:12:in `<top (required)>'
/Users/majobin/.rvm/gems/ruby-2.5.8/bin/rubocop:23:in `load'
/Users/majobin/.rvm/gems/ruby-2.5.8/bin/rubocop:23:in `<main>'
/Users/majobin/.rvm/gems/ruby-2.5.8/bin/ruby_executable_hooks:24:in `eval'
/Users/majobin/.rvm/gems/ruby-2.5.8/bin/ruby_executable_hooks:24:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Layout/SpaceAroundMethodCallOperator cop was inspecting /Users/majobin/code/iproj/app/views/api/v3/platform_identifiers/show.json.jbuilder:6:4.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.88.0 (using Parser 2.7.1.4, rubocop-ast 0.2.0, running on ruby 2.5.8 x86_64-darwin19)
Finished in 0.17962499998975545 seconds
```
## RuboCop version

> 0.88.0 (using Parser 2.7.1.4, rubocop-ast 0.2.0, running on ruby 2.5.8 x86_64-darwin19)

**Comment by koic** [comment]
This issue is a dup with #8324 and resolved by #8328. Can you update to the latest RuboCop? Thank you.
