### ISSUE TITLE
Consistent test failures due to test-queue?

### ISSUE THREAD

**Issue by dvandersluis** [rubocop-hq/rubocop#9179]
In the last day or so we've gotten consistent CI failures on ruby-head from `test-queue`:

```
/usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:330:in `write': Transport endpoint is not connected (Errno::ENOTCONN)
	from /usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:330:in `puts'
	from /usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:330:in `block (4 levels) in discover_suites'
	from /usr/local/lib/ruby/3.0.0/socket.rb:72:in `connect_internal'
	from /usr/local/lib/ruby/3.0.0/socket.rb:137:in `connect'
	from /usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:329:in `block (3 levels) in discover_suites'
	from /usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:326:in `each'
	from /usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:326:in `block (2 levels) in discover_suites'
	from /usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:325:in `each'
	from /usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:325:in `block in discover_suites'
	from /usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:319:in `fork'
	from /usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:319:in `discover_suites'
	from /usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:237:in `execute_internal'
	from /usr/local/bundle/gems/test-queue-0.4.2/lib/test_queue/runner.rb:129:in `execute'
	from tasks/spec_runner.rake:30:in `block in run_specs'
	from tasks/spec_runner.rake:44:in `with_encoding'
	from tasks/spec_runner.rake:28:in `run_specs'
	from tasks/spec_runner.rake:116:in `block in <top (required)>'
```

It doesn't appear that test_queue has been updated in quite some time (the last gem release was almost 4 years ago), but I'm wondering if maybe ruby-head was updated in some incompatible way.

**Comment by marcandre** [comment]
Interesting.
There's a lot of work being done currently on concurency (Ractor, but also @ioquatix's work on Fibers).
It would be interesting to be able to reproduce it and do a git bisect to figure out what's the commit responsible.

I tried `rake spec` on my mac and things run smoothly (ruby 3.0.0dev (2020-12-05T10:40:00Z master 9dbb2bfd73) [x86_64-darwin18])
Can you reproduce it on your machine?

**Comment by dvandersluis** [comment]
Installed `3.0.0-dev` (also on mac) and ran `bundle exec rake spec`, it succeeded with no errors. Only ever saw it in the CI reports.

```
ruby 3.0.0dev (2020-12-07T04:33:53Z master 5d8bcc4870) [x86_64-darwin18]
```

**Comment by koic** [comment]
Circle CI now passes. It seems that the Ruby head image of CI was temporarily broken. So I will close this issue.
OTOH, maybe it may be useful to display `ruby -v` in the CI results in future.
