### ISSUE TITLE
HTML formatter crashes on empty files

### ISSUE THREAD

**Issue by dvandersluis** [rubocop-hq/rubocop#9445]
Create an empty file and then run RuboCop on it, with `-f h`.

It'll crash with the following backtrace:

```
index 0 outside of array bounds: 0...0
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.0.0/lib/parser/source/buffer.rb:265:in `fetch'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.0.0/lib/parser/source/buffer.rb:265:in `source_line'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.0.0/lib/parser/source/range.rb:126:in `source_line'
(erb):246:in `block (2 levels) in binding'
(erb):239:in `each'
(erb):239:in `block in binding'
(erb):233:in `each'
(erb):233:in `binding'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/erb.rb:901:in `eval'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/erb.rb:901:in `result'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/formatter/html_formatter.rb:64:in `render_html'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/formatter/html_formatter.rb:49:in `finished'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/formatter/formatter_set.rb:34:in `public_send'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/formatter/formatter_set.rb:34:in `block (3 levels) in <class:FormatterSet>'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/formatter/formatter_set.rb:34:in `each'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/formatter/formatter_set.rb:34:in `block (2 levels) in <class:FormatterSet>'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/runner.rb:95:in `inspect_files'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/runner.rb:47:in `run'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/cli/command.rb:11:in `run'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/cli/environment.rb:18:in `run'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/cli.rb:65:in `run_command'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/cli.rb:72:in `execute_runners'
/Users/daniel/RubymineProjects/rubocop/lib/rubocop/cli.rb:41:in `run'
/Users/daniel/RubymineProjects/rubocop/exe/rubocop:13:in `block in <top (required)>'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Users/daniel/RubymineProjects/rubocop/exe/rubocop:12:in `<top (required)>'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/rubocop:23:in `load'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/rubocop:23:in `<top (required)>'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/Users/daniel/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
/Users/daniel/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
```

---

## RuboCop version
```
master
```

**Comment by dvandersluis** [comment]
Actually I can't duplicate this anymore... I wonder if it was a weird caching bug or something.
