### ISSUE TITLE
An error occurred while Style/DisableCopsWithinSourceCodeDirective cop was inspecting

### ISSUE THREAD

**Issue by MatUrbanski** [rubocop-hq/rubocop#9462]
I have a Ruby project that uses the 3.0.0 version, after upgrading to Rubocop 1.9.0 I receive the following errors when running `rubocop` command: 

```
.Scanning /Users/mateuszurbanski/projects/blog-api/system/boot/oj.rb
An error occurred while Style/DisableCopsWithinSourceCodeDirective cop was inspecting /Users/mateuszurbanski/projects/blog-api/system/boot/oj.rb.
undefined method `[]' for nil:NilClass
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/style/disable_cops_within_source_code_directive.rb:74:in `directive_cops'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/style/disable_cops_within_source_code_directive.rb:42:in `block in on_new_investigation'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/style/disable_cops_within_source_code_directive.rb:41:in `each'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/style/disable_cops_within_source_code_directive.rb:41:in `on_new_investigation'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/commissioner.rb:157:in `block (2 levels) in invoke'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/commissioner.rb:166:in `with_cop_error_handling'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/commissioner.rb:156:in `block in invoke'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/commissioner.rb:155:in `each'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/commissioner.rb:155:in `invoke'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/commissioner.rb:84:in `investigate'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/team.rb:157:in `investigate_partial'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cop/team.rb:83:in `investigate'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:315:in `inspect_file'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:286:in `loop'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:132:in `block in file_offenses'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:157:in `file_offense_cache'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:131:in `file_offenses'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:122:in `process_file'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:100:in `each'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:100:in `reduce'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:86:in `inspect_files'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/runner.rb:47:in `run'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cli.rb:65:in `run_command'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cli.rb:72:in `execute_runners'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/lib/rubocop/cli.rb:41:in `run'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/exe/rubocop:13:in `block in <top (required)>'
/Users/mateuszurbanski/.rubies/ruby-3.0.0/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
/Users/mateuszurbanski/.gem/ruby/3.0.0/gems/rubocop-1.9.0/exe/rubocop:12:in `<top (required)>'
/Users/mateuszurbanski/.gem/ruby/3.0.0/bin/rubocop:23:in `load'
/Users/mateuszurbanski/.gem/ruby/3.0.0/bin/rubocop:23:in `<main>'
```

**Comment by koic** [comment]
This issue is a dup with #9431 and resolved #9432. Thank you for your feedback!
