### ISSUE TITLE
pre-commit hook not working with multiple rubocop linters

### ISSUE THREAD

**Issue by mwolman** [rubocop-hq/rubocop#9488]
I'm trying to install the new pre-commit hook using `pre-commit`. This is my `.pre-commit-config.yaml` file

```yaml
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/rubocop-hq/rubocop
  rev: v1.9.1
  hooks:
    - id: rubocop
```

And this is the error I got when trying to make a commit:

```
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check for added large files..............................................Passed
rubocop..................................................................Failed
- hook id: rubocop
- exit code: 2

cannot load such file -- rubocop-rails
/Users/micaela/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/micaela/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/lib/rubocop/config_loader_resolver.rb:17:in `block (2 levels) in resolve_requires'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/lib/rubocop/config_loader_resolver.rb:13:in `each'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/lib/rubocop/config_loader_resolver.rb:12:in `tap'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/lib/rubocop/config_loader.rb:45:in `load_file'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/lib/rubocop/config_loader.rb:106:in `configuration_from_file'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/lib/rubocop/config_store.rb:69:in `for_dir'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/lib/rubocop/config_store.rb:48:in `for_pwd'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/lib/rubocop/cli.rb:128:in `apply_default_formatter'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/lib/rubocop/cli.rb:40:in `run'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/exe/rubocop:13:in `block in <top (required)>'
/Users/micaela/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/gems/rubocop-1.9.1/exe/rubocop:12:in `<top (required)>'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/bin/rubocop:23:in `load'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/bin/rubocop:23:in `<main>'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/bin/ruby_executable_hooks:24:in `eval'
/Users/micaela/.cache/pre-commit/repoy6rh2lbp/rbenv-default/gems/bin/ruby_executable_hooks:24:in `<main>'
```

How can I make it work together with `rubocop-rails` and `rubocop-rspec`? Is it possible?

```
1.9.1 (using Parser 3.0.0.0, rubocop-ast 1.4.1, running on ruby 2.7.2 x86_64-darwin19)
  - rubocop-rails 2.9.1
  - rubocop-rspec 2.1.0
```

**Comment by jdufresne** [comment]
@mwolman I've opened PR #9489 to document how to use pre-commit with extensions. Please let me know if it provides enough detail to alter the configuration to achieve your goals. Any feedback or guidance as to how to improve it further is welcome.

**Comment by mwolman** [comment]
@jdufresne it works perfectly now 🥳  thank you!
