### ISSUE TITLE
Style/HashConversion: Invalid conversion (undefined method `to_h')

### ISSUE THREAD

**Issue by jdufresne** [rubocop-hq/rubocop#9513]
Testing using RuboCop commit 2d3e1bc19660ec06d3efa43a1045c6ae34f016b9

```
$ bundle exec rubocop -V
1.9.1 (using Parser 3.0.0.0, rubocop-ast 1.4.1, running on ruby 2.7.2 x86_64-linux)
  - rubocop-performance 1.9.2
  - rubocop-rspec 2.0.1
```

Input file:

```rb
Hash[Integer => BigInteger]
```

Command

```rb
$ bundle exec rubocop -a --only Style/HashConversion ~/test.rb 
Inspecting 1 file
C

Offenses:

/home/jon/test.rb:1:1: C: [Corrected] Style/HashConversion: Prefer ary.to_h to Hash[ary].
Hash[Integer => BigInteger]
^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

Changed file:

```rb
Integer => BigInteger.to_h
```

Running the code now results in:

```
NoMethodError (undefined method `to_h' for BigInteger:Class)
Did you mean?  to_s
```

**Comment by RichardsonWTR** [comment]
@bbatsov, I've just experienced this same error  in Ruby 2.7.1p83.
```bash
$ bundle exec rubocop -V
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.2-compliant syntax, but you are running 2.7.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
1.10.0 (using Parser 3.0.0.0, rubocop-ast 1.4.1, running on ruby 2.7.1 x86_64-linux)
```
Input file:
```ruby 
hash1 = { 'some' => 'value', 'another' => 'value'  }
hash2 = { 'some' => 'value'}
hash1_without_hash2 = Hash[hash1.to_a - hash2.to_a]

p hash1_without_hash2
```
Code result:
```bash
$ ruby test.rb 
{"another"=>"value"}
```

Rubocop execution: 
```bash
$ bundle exec rubocop test.rb 
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.2-compliant syntax, but you are running 2.7.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Inspecting 1 file
C

Offenses:

test.rb:3:23: C: [Correctable] Style/HashConversion: Prefer ary.to_h to Hash[ary].
hash1_without_hash2 = Hash[hash1.to_a - hash2.to_a]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
```

After the execution of `bundle exec rubocop test.rb -a`
```ruby 
hash1 = { 'some' => 'value', 'another' => 'value' }
hash2 = { 'some' => 'value' }
hash1_without_hash2 = hash1.to_a - hash2.to_a.to_h

p hash1_without_hash2

```

Now the script causes an error. 
```bash
$ ruby test.rb 
Traceback (most recent call last):
        1: from test.rb:3:in `<main>'
test.rb:3:in `-': no implicit conversion of Hash into Array (TypeError)
```
Can you reopen this issue, or should I open a new issue?  By the way, is there a better way to write the above code?

**Comment by dvandersluis** [comment]
@RichardsonWTR can you make sure you're using the latest version of RuboCop and try again? If the problem persists, create a new ticket please. 🙌

**Comment by RichardsonWTR** [comment]
Thanks @dvandersluis
No need to open a new ticket.  
I've just tested with the 1.12.1 version and Rubocop worked as expected. Pure and simple solution.
